name: 'CI'

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install

  ci:
    runs-on: ubuntu-latest
    needs: [install] 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20   
      - name: Install
        run: yarn install 
      - name: Run pre-test containers
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_APP_DB: embleema_db
          MONGO_APP_USER: embleema_user
          MONGO_APP_PASSWORD: embleema_password         
        run: docker-compose -f "docker/docker-compose.yml" up -d --build
      - name: Run all
        env:
          VITE_KEYCLOAK_AUTH_URL: http://localhost:8080/realms/embleema-iam
          VITE_KEYCLOAK_AUTH_REDIRECT_URL: http://localhost:5173/
          VITE_KEYCOAK_CLIENT_ID: embleema-webapp      
          KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080
          KEYCLOAK_CLIENT_ID: embleema-api
          KEYCLOAK_REALM: embleema-iam
          KEYCLOAK_CLIENT_SECRET: GbM9bBMW9W7LYLyndNQobrBNWVDvDX6C
        run: yarn turbo ci --continue