name: 'CI'

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install

  ci:
    runs-on: ubuntu-latest
    needs: [install] 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20   
      - name: Install
        run: yarn install 
      - name: Run pre-test containers
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        run: docker-compose -f "docker/docker-compose.keycloak-dev.yml" up -d --build
      - name: Run all
        env:
          VITE_KEYCLOAK_AUTH_URL: http://localhost:8080/realms/test-iam
          VITE_KEYCLOAK_AUTH_REDIRECT_URL: http://localhost:5173/
          VITE_KEYCOAK_CLIENT_ID: test-webapp      
        run: yarn turbo ci --continue
