name: 'CI'

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20   
      - name: Install
        run: yarn install 
      - name: Run pre-test containers
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin       
        run: docker-compose -f "./docker/docker-compose.keycloak-dev.yml" up -d --build
      - name: Wait container startup (sleep)
        run: sleep 30s        
        
      - name: Run all
        env:
          VITE_KEYCLOAK_AUTH_URL: http://localhost:8080/realms/embleema-iam
          VITE_KEYCLOAK_AUTH_REDIRECT_URL: http://localhost:5173/
          VITE_KEYCOAK_CLIENT_ID: embleema-webapp      
          VITE_EMBLEEMA_API_URL: http://localhost:3000
          KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080
          KEYCLOAK_CLIENT_ID: embleema-api
          KEYCLOAK_REALM: embleema-iam
          KEYCLOAK_CLIENT_SECRET: GbM9bBMW9W7LYLyndNQobrBNWVDvDX6C
          PRISMA_FIELD_ENCRYPTION_KEY: k1.aesgcm256.PEkTo4C0zBhswRughc_dh10mX-58kCnuR25AEL1KrQY=
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: yarn turbo ci --continue